Numpy - Numerical Python

Python Indexing and Extraction

Numpy Operators

In [1]:
#by convention 
import numpy as np
#pip install numpy
import numpy as np

# mathematics with numpy , matices, diffreential equations,

In [6]:
? np

In [9]:
import scipy as sc

In [12]:
import stat as st

In [14]:
import statistics as st

['Counter',
 'Decimal',
 'Fraction',
 'NormalDist',
 'StatisticsError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_coerce',
 '_convert',
 '_exact_ratio',
 '_fail_neg',
 '_find_lteq',
 '_find_rteq',
 '_isfinite',
 '_normal_dist_inv_cdf',
 '_ss',
 '_sum',
 'bisect_left',
 'bisect_right',
 'erf',
 'exp',
 'fabs',
 'fmean',
 'fsum',
 'geometric_mean',
 'groupby',
 'harmonic_mean',
 'hypot',
 'itemgetter',
 'log',
 'math',
 'mean',
 'median',
 'median_grouped',
 'median_high',
 'median_low',
 'mode',
 'multimode',
 'numbers',
 'pstdev',
 'pvariance',
 'quantiles',
 'random',
 'sqrt',
 'stdev',
 'tau',
 'variance']

In [16]:
import numpy as np

In [18]:
my_list=[0,1,2,3]
type(my_list)

list

In [14]:
my_list=[0,1,2,3]
type(my_list)

list

In [19]:
arr1=np.array(my_list)

In [22]:
type(arr1)

numpy.ndarray

In [24]:
np.ndim(arr1)

1

In [25]:
arr2=[[1,2,3,4],[5,6,7,8]]

In [27]:
type(arr2)

list

In [29]:
xd=np.array(arr2)

In [35]:
xd.ndim

2

In [17]:
xy=np.array(my_list)
#np.array(my_list)
type(xy)

numpy.ndarray

In [23]:
matrix=[[1,2,3,4],[5,6,7,8]]
#matrix=[[1,2,3,4],[5,6,7,8]]

In [24]:
matrix

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [26]:
np.array(matrix)

numpy.ndarray

In [38]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:

np.arange(20,30,2.5)

array([20. , 22.5, 25. , 27.5])

In [42]:
#np.arange(start,stop,step)
np.arange(0,20,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [45]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.arange(0,10)
#np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
np.zeros(50) + 20

array([20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
       20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
       20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
       20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.])

In [52]:
np.ones(50) +10

array([11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.,
       11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.,
       11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.,
       11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.])

In [55]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:

np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
#Reshaping
a=np.arange(0,30)

#6 X 5
#10 x 3
#5x6

#1X30
#30 X1 




array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
a.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [61]:
a.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [63]:
a.reshape(6,5).ndim

2

In [65]:
a.ndim

1

In [67]:
#dim=(x,y,z,)

In [71]:
np.linspace(0,20,50)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [72]:
np.linspace(0,20,40)

array([ 0.        ,  0.51282051,  1.02564103,  1.53846154,  2.05128205,
        2.56410256,  3.07692308,  3.58974359,  4.1025641 ,  4.61538462,
        5.12820513,  5.64102564,  6.15384615,  6.66666667,  7.17948718,
        7.69230769,  8.20512821,  8.71794872,  9.23076923,  9.74358974,
       10.25641026, 10.76923077, 11.28205128, 11.79487179, 12.30769231,
       12.82051282, 13.33333333, 13.84615385, 14.35897436, 14.87179487,
       15.38461538, 15.8974359 , 16.41025641, 16.92307692, 17.43589744,
       17.94871795, 18.46153846, 18.97435897, 19.48717949, 20.        ])

In [73]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [81]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
np.random.rand(10)

array([0.79163276, 0.61920723, 0.36258224, 0.89042999, 0.05375182,
       0.74080448, 0.2606744 , 0.32452919, 0.31173256, 0.58555108])

In [101]:
np.random.randint(1000000)

740948

In [ ]:
np.

In [49]:

np.random.rand(10)

array([0.81805054, 0.0395813 , 0.63509031, 0.33795815, 0.983828  ,
       0.15820375, 0.1977572 , 0.39114898, 0.10452182, 0.92129424])

In [50]:
#Standard Normal Distribution
np.random.randn(10)

array([-1.61017347,  0.48628128, -0.7664976 ,  1.07295443,  1.19654492,
       -0.11254911,  0.68304994,  0.25914177, -0.77268974, -0.13356153])

In [3]:
import numpy as np
for i in range(0,5):
    print('Guessing Game between 1 to 10')
    user =int(input('Enter your number to win 20000'))
    bet=np.random.randint(10)


    if user==bet:
        print('Congratulation you have won')
    
    else:
        print('Try again Later')
        print('Your input ',user)
        print('Correct ans is ',bet)


Guessing Game between 1 to 10
Enter your number to win 200004
Try again Later
Your input  4
Correct ans is  1
Guessing Game between 1 to 10
Enter your number to win 200006
Try again Later
Your input  6
Correct ans is  5
Guessing Game between 1 to 10
Enter your number to win 200009
Try again Later
Your input  9
Correct ans is  3
Guessing Game between 1 to 10
Enter your number to win 200005
Try again Later
Your input  5
Correct ans is  0
Guessing Game between 1 to 10
Enter your number to win 200001
Try again Later
Your input  1
Correct ans is  9


In [82]:
print('Guessing Game between 1 to 10 ')
user=int(input('Enter a number '))
bet = np.random.randint(10)
if user ==bet:
    print('Correct')
else:
    print('ooooppps Try again later')
    print('The corret value is ', bet)
    


Guessing Game between 1 to 10 
Enter a number 8
ooooppps Try again later
The corret value is  0


In [6]:
np.random.randint(0,100,3)

array([15, 25, 66, 57, 98])

In [94]:
# selected Random Numbers
np.random.randint(0,2000,5)

array([1211, 1551, 1603,  589, 1812])

In [2]:
my_array=np.arange(1,10)

In [3]:
len(my_array)

9

In [4]:
my_array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
new_array=my_array.reshape(3,3)
type(new_array)


numpy.ndarray

In [6]:
number=np.append(my_array,100)

In [7]:
#Not a list an array
number.append(-100)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
number=np.append(number,-200)

In [8]:
number

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [9]:
#number.max()
np.max(number)

100

In [10]:

number.min()
#np.min(number)

1

In [11]:
# Index of maximun number
number.argmax()

9

In [12]:
# Index of minimum number
number.argmin()

0

Numpy Indexing and Extraction

In [15]:
number

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [16]:
number
number[1]

2

In [17]:
number[0:7]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
number[-3]

8

In [27]:
number
number=np.append(number,-200)
number[0]=15
number

array([  15,    2,    3,    4,    5,    6,    7,    8,    9,  100, -200,
       -200, -200, -200, -200, -200, -200, -200])

In [28]:
np.

array([  15,    2,    3,    4,    5,    6,    7,    8,    9,  100, -200,
       -200, -200, -200, -200, -200, -200, -200])

In [29]:
number

array([  15,    2,    3,    4,    5,    6,    7,    8,    9,  100, -200,
       -200, -200, -200, -200, -200, -200, -200])

In [31]:
number[5]=50
number

array([  15,    2,    3,    4,    5,   50,    7,    8,    9,  100, -200,
       -200, -200, -200, -200, -200, -200, -200])

In [33]:
number[0:4]=100

In [34]:
number[1]

array([ 100,  100,  100,  100,    5,   50,    7,    8,    9,  100, -200,
       -200, -200, -200, -200, -200, -200, -200])

In [62]:
def driving(speed,birthday):
    if birthday:
        speeding=speed-5
    else:
        speeding=speed
    if speeding >80:
        return "Big Ticket"
    
    elif speeding>60:
        return "Small Ticket"
    else:
        return "No ticket"

In [6]:
def driving(speed, birthday):
    if birthday:
        speeding=speed-5
    else:
        speeding=speed
    if speeding>80:
        print('Big Ticket')
    elif speeding>60:
        print('Small Ticket')
    else:
        print('No Ticket')

In [10]:
driving(83,False)

Big Ticket


In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
data=np.arange(5,50,)
data

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
len(data)

45

In [56]:
data.reshape(1,45)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
data.reshape(5,9)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [66]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45,]])
#arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [69]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
type(arr_2d)

numpy.ndarray

In [70]:
arr_2d[0]

array([ 5, 10, 15])

In [71]:
arr_2d[1]

array([20, 25, 30])

In [72]:
arr_2d[2]

array([35, 40, 45])

In [78]:
arr_2d[0][2]

15

In [79]:
arr_2d[1][1]

25

In [87]:
arr_2d[:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [91]:
arr_2d[1:2]

array([[20, 25, 30]])

In [92]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [84]:
#Boolean

In [94]:
x=np.arange(0,11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
x>0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [96]:
x>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [98]:
#To see the boolean Arguement
x[x>5]

array([ 6,  7,  8,  9, 10])

In [100]:
x[x==6]
#x[x==6]

array([6])

In [111]:
new_data=np.arange(50).reshape(5,10)

In [112]:
new_data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [145]:
#new_data[1:3,3:5]
new_data[2:4,6:8]

array([[26, 27],
       [36, 37]])

 Array With Array
 
 Array with Scalar
 
 Universal Array Function

In [166]:
arr=np.arange(11)


In [167]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [168]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [169]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [170]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [171]:
arr-10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [172]:
arr/arr

<ipython-input-172-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [173]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [174]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [176]:
np.sqrt(arr)
#np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [177]:
np.max(arr)

10

In [178]:
np.min(arr)

0

In [179]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [185]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [186]:
np.log(arr)

<ipython-input-186-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [187]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

np Exericse
import numerical python

create an array of 10 zeros

create an array of 10 ones

create an array of 10 fives

create an array of integers from 10 to 50 

create a 3*3 matrix  with values ranging from 0 to 8

create a numpy to generate a random number between 0 and 1


create a numpy to generate an array of 25 random numbers sampled from a standard normal distribution 

create a array for 20 lineary spaced points between 0 and 1

create a 5*5 array with values ranging from 1 to 26


generate the output

1)array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
       
       
2)     20


3)    array([[ 2],
       [ 7],
       [12]])
       
       
4)  get the sum of all the values 

5)  The standard deviation


6) Get the sum of all the columns 


7) Get the sum of all the rows



In [205]:
dat=np.arange(1,26).reshape(5,5)
#np.sqrt(100)

In [193]:
dat[2:,1:]
#dat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [196]:
dat[0:3,1:2]
#dat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [197]:
dat[4]

array([21, 22, 23, 24, 25])

In [202]:
lst=[x for x in range(10,20)]
lst


[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [149]:
dat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [151]:
import pickle as pk

In [152]:
model=pk.load(open('svc.pkl','rb'))

In [153]:
model

SVC(kernel='linear')

In [154]:
model.predict_proba([3,4,5,6,7,8,])

AttributeError: predict_proba is not available when  probability=False

In [146]:
import pandas as pd

In [154]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [207]:
a=np.array([[3,6],[7,9]])

In [208]:
a

array([[3, 6],
       [7, 9]])

In [209]:
b=np.array([[4,8],[10,12]])

In [210]:
b

array([[ 4,  8],
       [10, 12]])

In [211]:
a*b

array([[ 12,  48],
       [ 70, 108]])

In [ ]:
np.